# Exercícios - Salarios de São Francisco

Bem-vindo a um exercício rápido para você praticar suas habilidades de pandas! Vamos usar o [Dataset SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) da Kaggle! Basta acompanhar e completar as tarefas descritas em negrito abaixo. As tarefas se tornarão cada vez mais difíceis.

** Importe o pandas como pd.**

In [1]:
import numpy as np
import pandas as pd

** Leia o arquivo Salaries.csv como um DataFrame chamado "sal". **

In [2]:
sal = pd.read_csv("Salaries.csv", index_col="Id")
sal

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
Id,,,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [3]:
sal.head()

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
Id,,,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

** Verifique o "head" do DataFrame. **

** Use o método .info () para descobrir quantas entradas existem. **

In [4]:
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 1 to 148654
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  str
 1   JobTitle          148654 non-null  str
 2   BasePay           148045 non-null  float64
 3   OvertimePay       148650 non-null  float64
 4   OtherPay          148650 non-null  float64
 5   Benefits          112491 non-null  float64
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
 9   Notes             0 non-null       float64
 10  Agency            148654 non-null  str
 11  Status            0 non-null       float64
dtypes: float64(8), int64(1), str(3)
memory usage: 20.2 MB

** Qual é o "BasePay" médio? **

In [5]:
sal["BasePay"].mean()

np.float64(66325.44884048769)

** Qual é a maior quantidade de "OvertimePay" no conjunto de dados? **

In [6]:
sal["OvertimePay"].max()

np.float64(245131.88)

** Qual é o cargo de JOSEPH DRISCOLL? Nota: use todas as maiúsculas, caso contrário você pode obter uma resposta que não coincida (há também um Joseph Driscoll com minúsculas). **

In [7]:
a = sal['EmployeeName'].str.contains("JOSEPH DRISCOLL")
sal['JobTitle'][a]

Id
25    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

** Quanto JOSEPH DRISCOLL ganha (incluindo benefícios)? **

In [8]:
a = sal['EmployeeName'].str.contains("JOSEPH DRISCOLL")
sal['TotalPayBenefits'][a]

Id
25    270324.91
Name: TotalPayBenefits, dtype: float64

** Qual o nome da pessoa mais bem paga (incluindo benefícios)? **

In [9]:
cond = sal["TotalPayBenefits"].idxmax()
sal.loc[cond, "EmployeeName"]

'NATHANIEL FORD'

** Qual o nome da pessoa paga mais baixa (incluindo benefícios)? Você percebe algo estranho sobre o quanto ele ou ela é paga? **

In [10]:
cond = sal["TotalPayBenefits"].idxmin()
sal.loc[[cond]]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
Id,,,,,,,,,,,,
148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

** Qual foi a média (média) BasePay de todos os funcionários por ano? (2011-2014)? **

In [11]:
for i in range(2011, 2015):
    print(i, sal.loc[sal['Year'] == i, 'BasePay'].mean())

2011 63595.95651677314
2012 65436.40685742262
2013 69630.03021648063
2014 66564.42192449959

** Quantos títulos de trabalho únicos existem? **

In [12]:
len(sal["JobTitle"].unique())

2159

** Quais são os 5 principais empregos mais comuns? **

In [13]:
g = sal['JobTitle'].value_counts()
g[0:5]

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

** Quantos Títulos de Trabalho foram representados por apenas uma pessoa em 2013? (Por exemplo, títulos de trabalho com apenas uma ocorrência em 2013?) **

In [14]:
h = sal[sal['Year'] == 2013]
i = h['JobTitle'].value_counts()
i[i == 1].count()

np.int64(202)

** Quantas pessoas têm a palavra Chefe em seu cargo? (Isso é bastante complicado) **

In [15]:
j = sal[sal['JobTitle'].str.contains('Chief')]
j

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
Id,,,,,,,,,,,,
36161,Gregory Suhr,Chief of Police,302578.00,0.00,18974.11,69810.19,321552.11,391362.30,2012,NaN,San Francisco,NaN
36163,Joanne Hayes-White,"Chief, Fire Department",296943.01,0.00,17816.59,72047.88,314759.60,386807.48,2012,NaN,San Francisco,NaN
36170,Brendan Ward,"Battlion Chief, Fire Suppressi",174822.47,118215.58,28845.78,49648.09,321883.83,371531.92,2012,NaN,San Francisco,NaN
36171,Samson Lai,"Battlion Chief, Fire Suppressi",174822.44,112731.28,28660.28,53249.56,316214.00,369463.56,2012,NaN,San Francisco,NaN
36172,Rudy Castellanos,"Battlion Chief, Fire Suppressi",176771.74,124413.13,15803.39,52320.90,316988.26,369309.16,2012,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
138012,Sharon C Jackson,Chief Deputy Adlt Probation Of,56660.18,0.00,0.00,566.61,56660.18,57226.79,2014,NaN,San Francisco,NaN
139621,Anita S Lee,Chief Clerk,38598.86,0.00,0.00,386.00,38598.86,38984.86,2014,NaN,San Francisco,NaN
139710,George D Vaughan,Chief Nursery Specialist,27319.47,483.90,0.00,10334.67,27803.37,38138.04,2014,NaN,San Francisco,NaN
140081,Patrick W Gillespie,Chief Preparator,24091.00,0.00,0.00,10176.77,24091.00,34267.77,2014,NaN,San Francisco,NaN
140157,Christopher L Ochoa,Chief Stationary Engineer,24392.00,418.71,0.00,8918.44,24810.71,33729.15,2014,NaN,San Francisco,NaN

** Bônus: Existe uma correlação entre o comprimento da seqüência do título do trabalho e o salário? **

In [16]:
sal["title_len"] = sal["JobTitle"].str.len()
corre = sal["title_len"].corr(sal["TotalPayBenefits"])
corre

np.float64(-0.03687844593260706)