In [6]:
import numpy as np
import pandas as pd

In [7]:
#Niveis de Indice
outside = ["G1",  "G1", "G1", "G2", "G2", "G2"]
inside = [1, 2, 3, 1, 2, 3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [8]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [9]:
inside

[1, 2, 3, 1, 2, 3]

In [10]:
#recebe 2 lista e transforma-as em uma tupla
hier_index = list(zip(outside, inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [11]:
#recebe a tupla e transforma em um indice multiplo
hier_index = pd.MultiIndex.from_tuples(hier_index)
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [12]:
#cria o df com indices multiplos
df = pd.DataFrame(np.random.randn(6,2), index=hier_index, columns = ["A", "B"])
df

             A         B
G1 1  1.001978 -2.201811
   2 -0.360465 -0.548391
   3  1.485634  0.128546
G2 1  0.306072 -0.030141
   2 -1.771754 -0.924284
   3 -0.735790 -1.909623

In [11]:
#permite analisar todos que contem o indice maior
df.loc["G1"]

          A         B
1  0.974131 -0.770635
2  1.651256  0.699931
3 -0.725132 -0.756210

In [19]:
#permite localizar o mais interno ao tratar o df.loc["G1"] como um DataFrame separado
df.loc["G1"].loc[1]

A    0.974131
B   -0.770635
Name: 1, dtype: float64

In [21]:
#procura os nomes dos indices
df.index.names

FrozenList([None, None])

In [23]:
#define os nomes dos indices mais externos para mais interno
df.index.names = ["Grupo", "Numero"]

In [24]:
#faz uma seção transversal, bom para acessar os indices mais externos
df.xs(1, level="Numero")

              A         B
Grupo
G1     0.974131 -0.770635
G2    -0.800305  1.396758